name: build

on:
  push:
    branches:
      - master

jobs:
  publish-dev-package:
    runs-on: ubuntu-latest
    if: github.repository == 'aerokube/cypress-moon'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          always-auth: true
          registry-url: https://registry.npmjs.org
          scope: '@aerokube'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test

      - run: ci/publish.sh snapshot
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
